### ISSUE TITLE
AlreadySentError raised from Appsignal.Plug.handle_error/5

### ISSUE THREAD

**Issue by mbuhot** [appsignal/appsignal-elixir-plug#26]
If an error occurs after the response has been sent, `Appsignal.Plug.handle_error/5`  fails with `AlreadySentError` from the usage of `Plug.Conn.put_status`: https://github.com/appsignal/appsignal-elixir-plug/blob/main/lib/appsignal_plug.ex#L135

The docs for `Plug.Conn.put_status` suggests to only try to set the status the Conn state is not `:sent` or `:chunked`.

**Comment by tombruijn** [comment]
Hi @mbuhot! Thanks for the report. We're going to look into it.

**Comment by jeffkreeftmeijer** [comment]
Hey @mbuhot,

Thanks for reporting this issue. This seems like it’d fail in the current implementation indeed. I’ve been working on reproducing this, but I haven’t gotten it to fail. In https://github.com/appsignal/appsignal-elixir-plug/commit/2fb42437cb0d61c0ec39f56d0902651e39b81e49, I’ve added a test case that uses an endpoint that returns a response before raising the error;

``` elixir
get "/already-sent” do
  send_resp(conn, 200, "Exception!")
  raise "Exception!"
end
```

However, since the `conn` that has its status updated is not the same `conn` that the error handler receives, my test doesn’t run into that `AlreadySentError`.

Could you show me an example of how this failing scenario looks for you, so we can add it to the test suite and make sure setting the response code only happens when the response isn’t yet sent?
